// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelMerge() {
  return window['go']['main']['App']['CancelMerge']();
}

export function GenerateThumbnail(arg1) {
  return window['go']['main']['App']['GenerateThumbnail'](arg1);
}

export function GetHardwareEncoders() {
  return window['go']['main']['App']['GetHardwareEncoders']();
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetVideoMetadata(arg1) {
  return window['go']['main']['App']['GetVideoMetadata'](arg1);
}

export function MergeVideos(arg1) {
  return window['go']['main']['App']['MergeVideos'](arg1);
}

export function SelectVideos() {
  return window['go']['main']['App']['SelectVideos']();
}

export function SetUseHardwareEncoder(arg1) {
  return window['go']['main']['App']['SetUseHardwareEncoder'](arg1);
}
