// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelMerge():Promise<void>;

export function GenerateThumbnail(arg1:string):Promise<string>;

export function GetPresets():Promise<Array<main.MergePreset>>;

export function MergeVideos(arg1:Array<main.VideoFile>):Promise<string>;

export function SelectVideos():Promise<Array<main.VideoFile>>;
