// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateThumbnail(arg1) {
  return window['go']['main']['App']['GenerateThumbnail'](arg1);
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function MergeVideos(arg1) {
  return window['go']['main']['App']['MergeVideos'](arg1);
}

export function SelectVideos() {
  return window['go']['main']['App']['SelectVideos']();
}
